version: '3.8'

services:
  # Laravel Backend
  backend:
    build:
      context: ./backend
    container_name: laravel-backend
    volumes:
      - ./backend:/var/www
    networks:
      - app-network
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=dokik_nav
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - db

  # React Frontend
  frontend:
    build:
      context: ./frontend
    container_name: react-frontend
    ports:
      - 3000:3000
    networks:
      - app-network
    depends_on:
      - backend

  # MySQL
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dokik_nav
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 
    ports:
      - 8080:80
    networks:
      - app-network
    depends_on:
      - db

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
    driver: local
